### ISSUE TITLE
Add instruction for build

### ISSUE THREAD

**Issue by Ste74** [juhaku/loginized#11]
Hello, I want to test your program and I am also thinking of including it in Manjaro but I would like to have instructions for its compilation. You provide precompiled files for distributions but I need to write the **PKGBUILD** to be able to pack it. Alternatively I could use the **.deb** package but I do not like it.

Cheers
Stefano Capitani
Manjaro Team

**Comment by juhaku** [comment]
Hi, indeed. I'll provide the build instructions in a short while.

**Comment by juhaku** [comment]
And there you go: https://github.com/juhaku/loginized/wiki#build-application-from-sources
Hope this helps and get's you forward with testing.. If you need anything don't hesitate to contact me.

-Juha

**Comment by Ste74** [comment]
Thanks, everything works as it should.
Some considerations:

- Why is it mandatory to choose the theme and it is not possible to just add the image?
- How do you deal with gnome-shell updates? Is everything reset or are your changes maintained?

**Comment by juhaku** [comment]
Good to know.. Replies to the questions.
 * This was just the way I thought it is best. At least I want to change the theme as well and the images along with it. However I could give some thought for the UI so that you may choose only images. But furthermore in the theme list there is selection `Default` just for that scenario you wish to update only the images. Default points to latest updated theme .gresource file before first start up of the UI. This can be updated manually via settings. 
* What comes for shell updates currently there is no way to recognize whether the gnome-shell is updated or not. Just for a thought as you mentioned not sure whether there is a way to write a shell script hook to that run's specific shell script after the gnome-shell is updated that could resolve automatic settings restoration. Currently if gnome-shell updates the update will rewrite the latest gnome-shell.gresource from /usr/share/gnome-shell/ folder. However the UI application remembers latest saved settings so when UI application is launched then previous settings can be easily saved again.

**Comment by Ste74** [comment]
> Currently if gnome-shell updates the update will rewrite the latest `gnome-shell-theme.gresource` from `/usr/share/gnome-shell/` folder. However the UI application remembers latest saved settings so when UI application is launched then previous settings can be easily saved again.

In Arch/Manjaro we have a hook function used with pacman so in Manjaro i use this to check / compare the .gresource file and reapply if needed. Another way for systemd system ( and gnome is systemd centric ) can be use a systemd service for comparision . Do you think?

**Comment by juhaku** [comment]
Sounds good. I need to take a look at alternatives. It would be best to get some sort of general solution for multiple platforms. It would be not ideal to write huge number of lines of code just for each distribution. Currently I have no idea of implemenation of this kind of script of where to place such. But I'll do some digging. Also any ideas or even examples are welcome as I am totally "greenhorn" in these hooks.
