### ISSUE TITLE
fails to save with error message ubuntu 19.04

### ISSUE THREAD

**Issue by lukeshaughnessy** [juhaku/loginized#12]
Choose file, press save and receive this error:

/opt/Loginized/loginized-cli.sh: line 176: glib-compile-resources: command not found cp: cannot stat '/tmp/shell/theme/gnome-shell-theme.gresource': No such file or directory

**Comment by juhaku** [comment]
Hello, did you read these instructions: https://github.com/juhaku/loginized/wiki#install-instructions-for-debian-based-distros

Also there are couple of closed issues of the same issue but older versions.. ([#3](https://github.com/juhaku/loginized/issues/3) [#4](https://github.com/juhaku/loginized/issues/4)) The issue is basically because you do not have the command in your system installed by default. You can test whether the command is at your system with commands below in your terminal. 
```
$ whereis glib-compile-resources 
glib-compile-resources: /usr/bin/glib-compile-resources /usr/share/man/man1/glib-compile-resources.1.gz
$ which glib-compile-resources
/usr/bin/glib-compile-resources
```
After installing required packages to the system you should be able to save the theme. Installation is described in the first link to installation instructions.

If you still encounter the issue after these steps has been verified I'll start debuggin and come back to you with better time.

Cheers
/Juha
