### ISSUE TITLE
sed error in loginized-cli

### ISSUE THREAD

**Issue by BenMorel** [juhaku/loginized#16]
Hi, I've been following the instructions on [the wiki](https://github.com/juhaku/loginized/wiki/Help) to add a custom theme:

    # cd /usr/share/themes/Pop/gnome-shell/
    # loginized-cli compile

But I get this error:

> sed: -e expression #1, char 0: no previous regular expression

**Comment by juhaku** [comment]
Okay, can you provide me the theme by attaching those theme files here and
information of which system you are using? I can try to debug it when i
have time. Been really busy with other things recently.

**Comment by juhaku** [comment]
Hi thinkin this more the issue is at the command execution. It does not provide good error message that would be clear to users. But the issue is the command you have typed. You have typed __loginized-cli compile__ which instead should have the __loginized-cli compile .__ Note! the last dot (.) at the end of command. I will add that to the install instruction details.

**Comment by BenMorel** [comment]
Oops, sorry about that, I indeed missed the dot!
