### ISSUE TITLE
No restore option

### ISSUE THREAD

**Issue by ZicPL** [juhaku/loginized#18]
Hi, great addon for gnome but I see there is no restore option :P
I tried clear background in Loginzed and this nothing change after reboot..

**Comment by ZicPL** [comment]
I saw: "Please backup default /usr/share/gnome-shell/gnome-shell-theme.gresource file before using Loginized in case it need to be reverted." too late for me :P

**Comment by juhaku** [comment]
Hi, thanks and great that you have liked it. In order to clear selected background you should be able to do it just by clearing the background and then saving again without background. In other cases further debugging might be needed. Im just been awfully busy with other stuff in these recent days and not having enough time to spend on this app.

Also to the /usr/share/gnome-shell/gnome-shell-theme.gresource file. By default if you did not have a modified version of the gnome shell theme installed before. You can find backup of default gnome-shell theme taken by the Loginized app from __/home/USER/.Loginized/default__. You can set that to the __/usr/share/gnome-shell/__ folder to revert back to original theme as well. 

Cheers
-Juha

**Comment by ZicPL** [comment]
Thank you for your quick support/response. I compiled "gresource" again. My issue is just a feature proposition and nothing more :)
I think that I'd close it :)

**Comment by juhaku** [comment]
Right.. yeah true it could have a button such called "Reset Defaults". :) Once I have more time I might add that.

**Comment by juhaku** [comment]
This kind of feature was added to the latest release. :clinking_glasses:
