### ISSUE TITLE
Not working on Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by mansoormemon** [juhaku/loginized#37]
I used loginized on `Arch Linux` to change my login screen theme and It worked fine. But, when I tried it on `Ubuntu 20.04 LTS` its not working.

**Comment by mansoormemon** [comment]
Everytime I reboot my PC the theme is set back to Default.

**Comment by juhaku** [comment]
Okay, Good notice, unfortunately I haven't had time and interest to test this in Ubuntu 20.04 at all and I'm too busy with my current job establishment to even consider debugging changes that Ubuntu has made since their last release. :( Indeed Arch has the best support for now since Im also arch based user but not using Gnome anymore for quite some time thus testing is lacking. So all in all this is the bitter fact that must be accepted for now on that I'm unable to provide multi-disto-support for the application.

But PR:s are welcome if there is enough interest: See https://github.com/juhaku/loginized#contributing

-Cheers
Juha

**Comment by mansoormemon** [comment]
Ok.
