### ISSUE TITLE
clarifying question for an Ubuntu 18.04 user

### ISSUE THREAD

**Issue by thedonquixotic** [juhaku/loginized#5]
I see that you have two closed issues from users who were using Ubuntu 18. Have those issues been fixed in the code itself or will I need to finangle some stuff? I'm very new to Linux and I don't want to screw up my settings but I was curious what was possible. 

Also does this work for GDM3? Or do I have to install an old version of GDM? And if I can use GDM3 with this, then where do I get themes, as to my knowledge GDM3 does not have themes? Do I just use GDM themes?

**Comment by juhaku** [comment]
Hello,

Actually what comes to fix, there is nothing that can fix in in the code. Issue is fixed by itself when the required package is installed to machine. :) As it is said in README that make sure `libglib2.0-dev-bin` package is being installed on Ubuntu 18.04. Ubuntu has not provided this package in default install and so need to be installed manually. This package provides functions that this application relies on when it comes to compiling the themes. Sure the information could be put more clear way.

Also for confusion in GDM. GDM is login manager for linux there are others as well but this is default to Gnome. It itself does not have themes that's true. But GDM uses precompiled system themes at login screen and this is what the application is for. It is to edit, compile and to set themes as system theme. 

Normally if one want's to change theme in login screen. A theme first should be decompiled to sources then required changes should be made sources and again compiled to `.gresource` package. After couple of times repeating this process get's bit furstrating.

Themes that can be installed are themes for Gnome GTK3. Some can be found from: https://www.gnome-look.org/browse/cat/135/ord/latest/ where some are good and others less complete or visually atractive. But the following one: https://github.com/adapta-project/adapta-gtk-theme is really comprehensive and provides quite nice polish to the Gnome.

By default you cannot change much in Gnome. Specifically via default settings manager you can only change wallpaper and lock screen shield. But the shield is not applied to login screen. But to be able to tweak the Gnome you need to have installed application called `gnome-tweak-tools`. This provides cabability to change more settings in Gnome including theme.

Hope this story was claryfing

**Comment by thedonquixotic** [comment]
Thank you, that does clarify things for me a bit.
