### ISSUE TITLE
Installed the provided rpm,does not appear on my app list

### ISSUE THREAD

**Issue by ahloiscreamo** [juhaku/loginized#7]
i try to find via terminal, no luck.
loginized also not appear on my application launcher
os-fedora29

**Comment by juhaku** [comment]
Thanks for notice, I'll check this out.. and I get back to you when I have some news related to this.

**Comment by juhaku** [comment]
I downloaded fedora 29 and installed it as virtual computer to test this situation. I downloaded the latest Loginized-0.2.5 rpm version and installed via command in terminal. `dnf localinstall Loginized_0.2.5_x64.rpm` Application did install correctly without any issues. It also appeared to the applications menu. 

However in order to launch the application you need to install following package in order to run the application __libXScrnSaver.x86_64__ 

The application is named __Loginized__ to search application you can use command's like `whereis Loginized` and `which Loginized` these commands should give you locations like __/usr/bin/Loginized__ which is the executable binary of the Loginized and __/usr/share/Loginized__ which is the install folder of the Loginized application. also the command line interface for the loginized is called __loginized-cli__ this will be installed after the first startup of the application. The location for __loginized-cli__ should be __/usr/bin/loginized-cli__

If any of locations is missing, or the /usr/share/Loginized is not a directory nor the /usr/share/Loginized is executable binary then something has gone wrong in installation and you need to reinstall the application. Aslo remove these existing files if necessary to give fresh base for installation.

**Comment by juhaku** [comment]
Also to furhter comment on this in order to show the application in application menu there should be desktop file for loginized in __/usr/share/applications/Loginized.desktop__ also the config's of the file is located in __/home/<user>/.config/Loginized__ this folder can be safely deleted and it will be recreated every launch if it does not exists. However deleting the folder you loose existing setups of the application. But it is good to delete to give fresh base for reinstallation.

**Comment by ahloiscreamo** [comment]
Hi @juhaku 
Thanks for the update,
the package libXScrnSaver.x86_64 already installed in my system
```
~
❯ su -
Password: 
[root@fedora-ahloi]~# dnf install libXScrnSaver
Last metadata expiration check: 0:52:12 ago on Wed 02 Jan 2019 09:42:05 PM +08.
Package libXScrnSaver-1.2.3-2.fc29.x86_64 is already installed.
Package libXScrnSaver-1.2.3-2.fc29.i686 is already installed.
Dependencies resolved.
Nothing to do.
Complete!
[root@fedora-ahloi]~# 

```
I forgot before posting the issues i did trying to search the installed location with that command (which)
without any luck
```
[root@fedora-ahloi]~# which loginized
/usr/bin/which: no loginized in (/usr/libexec/python2-sphinx:/usr/lib64/qt-3.3/bin:/usr/share/Modules/bin:/usr/lib64/ccache:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin)
[root@fedora-ahloi]~# 

```
but weird things is i actually found where they installed in /usr/share/Loginized/
,makes my head scratchy on why it did not installed in bin.

so i just click on the launcher and they work fine
thank you for your assisting and trouble, (yours went all the way trouble vm fedora etc, really appreciate it.)!
